apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: core-service
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: core-service
      previewService: core-service-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core-service
        image: <account-id>.dkr.ecr.<region>.amazonaws.com/core-service:latest
        ports:
        - containerPort: 8080
