apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-demo
  namespace: argocd
spec:
  project: blue-green-demo
  source:
    repoURL: https://github.com/Sunitha82/Blue-green-K8s.git
    targetRevision: HEAD
    path: overlays/blue-active  # Initially pointing to blue
  destination:
    server: https://kubernetes.default.svc
    namespace: blue-green-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
