apiVersion: v1
kind: Service
metadata:
  name: app-green-svc
  namespace: blue-green-demo
spec:
  selector:
    app: myapp
    version: green
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP