apiVersion: v1
kind: Service
metadata:
  name: app-production
  namespace: blue-green-demo
  labels:
    app: myapp
    role: production
spec:
  selector:
    app: myapp
    # The active version is not specified here, it will be patched
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer